name: Make release & publish Docker image

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        runner-platform:
          - ubuntu-latest
        include:
          - runner-platform: ubuntu-latest
            build-arch: linux/amd64,linux/arm64,linux/arm/v7
    runs-on: ${{ matrix.runner-platform }}
    steps:
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-prs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-prs

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: petertrr
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: codetheweb/muse:${{ github.sha }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=min
          build-args: |
            COMMIT_HASH=${{ github.sha }}
            BUILD_DATE=${{ steps.current-time.outputs.time }}
